---
netscalers:
  "netscaler1"
    ip: 192.168.1.1
    vservers:
      - lbname1
      - lbname2
    username: "user"
    password: "password"
  "netscaler2"
    ip: 192.168.1.2
    vservers:
      - lbname1
      - lbname2
    username: "user"
    password: "password"
  "netscaler3"
    ip: 192.168.1.3
    vservers:
      - lbname1
      - lbname2
    username: "user"
    password: "password"
   
rabbit_hosts:
 - cony47-2.mobile.rz
 - cony46-2.mobile.rz
 - cony38-3.mobile.rz
