---
"netscaler1":
  ip: 192.168.1.1
  vservers:
    - lb-name1 
    - lb-name2 
  username: user
  password: password-secret
"netscaler2":
  ip: 192.168.1.2
  vservers:
    - lb-name1 
    - lb-name2 
  username: user
  password: password-secret
"netscaler3":
  ip: 192.168.1.3
   vservers:
    - lb-name1 
    - lb-name2 
   username: user
   password: password-secret
   
rabbit_hosts:
 - host1
 - host2
 - host3
